/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ConditionsInscriptionRouteImport } from './routes/conditions-inscription'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RetrouverMonBadgeRouteImport } from './routes/retrouver-mon-badge'
import { Route as ApiSyncPaymentSecretRouteImport } from './routes/api.sync-payment-secret'
import { Route as ConfirmationRegistrationIdRouteImport } from './routes/confirmation.$registrationId'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffSignupRouteImport } from './routes/staff.signup'
import { Route as ApiWebhooksPaytechRouteImport } from './routes/api.webhooks.paytech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsInscriptionRoute = ConditionsInscriptionRouteImport.update({
  id: '/conditions-inscription',
  path: '/conditions-inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrouverMonBadgeRoute = RetrouverMonBadgeRouteImport.update({
  id: '/retrouver-mon-badge',
  path: '/retrouver-mon-badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncPaymentSecretRoute = ApiSyncPaymentSecretRouteImport.update({
  id: '/api/sync-payment-secret',
  path: '/api/sync-payment-secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRegistrationIdRoute =
  ConfirmationRegistrationIdRouteImport.update({
    id: '/confirmation/$registrationId',
    path: '/confirmation/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff/signup',
  path: '/staff/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaytechRoute = ApiWebhooksPaytechRouteImport.update({
  id: '/api/webhooks/paytech',
  path: '/api/webhooks/paytech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/checkin': typeof CheckinRoute
  '/conditions-inscription': typeof ConditionsInscriptionRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/retrouver-mon-badge': typeof RetrouverMonBadgeRoute
  '/api/sync-payment-secret': typeof ApiSyncPaymentSecretRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
  '/api/webhooks/paytech': typeof ApiWebhooksPaytechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/checkin': typeof CheckinRoute
  '/conditions-inscription': typeof ConditionsInscriptionRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/retrouver-mon-badge': typeof RetrouverMonBadgeRoute
  '/api/sync-payment-secret': typeof ApiSyncPaymentSecretRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
  '/api/webhooks/paytech': typeof ApiWebhooksPaytechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/checkin': typeof CheckinRoute
  '/conditions-inscription': typeof ConditionsInscriptionRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/retrouver-mon-badge': typeof RetrouverMonBadgeRoute
  '/api/sync-payment-secret': typeof ApiSyncPaymentSecretRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
  '/api/webhooks/paytech': typeof ApiWebhooksPaytechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/checkin'
    | '/conditions-inscription'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/inscription'
    | '/mentions-legales'
    | '/retrouver-mon-badge'
    | '/api/sync-payment-secret'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
    | '/api/webhooks/paytech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/checkin'
    | '/conditions-inscription'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/inscription'
    | '/mentions-legales'
    | '/retrouver-mon-badge'
    | '/api/sync-payment-secret'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
    | '/api/webhooks/paytech'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/checkin'
    | '/conditions-inscription'
    | '/confidentialite'
    | '/contact'
    | '/dashboard'
    | '/inscription'
    | '/mentions-legales'
    | '/retrouver-mon-badge'
    | '/api/sync-payment-secret'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
    | '/api/webhooks/paytech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CheckinRoute: typeof CheckinRoute
  ConditionsInscriptionRoute: typeof ConditionsInscriptionRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RetrouverMonBadgeRoute: typeof RetrouverMonBadgeRoute
  ApiSyncPaymentSecretRoute: typeof ApiSyncPaymentSecretRoute
  ConfirmationRegistrationIdRoute: typeof ConfirmationRegistrationIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffSignupRoute: typeof StaffSignupRoute
  ApiWebhooksPaytechRoute: typeof ApiWebhooksPaytechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-inscription': {
      id: '/conditions-inscription'
      path: '/conditions-inscription'
      fullPath: '/conditions-inscription'
      preLoaderRoute: typeof ConditionsInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrouver-mon-badge': {
      id: '/retrouver-mon-badge'
      path: '/retrouver-mon-badge'
      fullPath: '/retrouver-mon-badge'
      preLoaderRoute: typeof RetrouverMonBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-payment-secret': {
      id: '/api/sync-payment-secret'
      path: '/api/sync-payment-secret'
      fullPath: '/api/sync-payment-secret'
      preLoaderRoute: typeof ApiSyncPaymentSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$registrationId': {
      id: '/confirmation/$registrationId'
      path: '/confirmation/$registrationId'
      fullPath: '/confirmation/$registrationId'
      preLoaderRoute: typeof ConfirmationRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/signup': {
      id: '/staff/signup'
      path: '/staff/signup'
      fullPath: '/staff/signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paytech': {
      id: '/api/webhooks/paytech'
      path: '/api/webhooks/paytech'
      fullPath: '/api/webhooks/paytech'
      preLoaderRoute: typeof ApiWebhooksPaytechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CheckinRoute: CheckinRoute,
  ConditionsInscriptionRoute: ConditionsInscriptionRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RetrouverMonBadgeRoute: RetrouverMonBadgeRoute,
  ApiSyncPaymentSecretRoute: ApiSyncPaymentSecretRoute,
  ConfirmationRegistrationIdRoute: ConfirmationRegistrationIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffSignupRoute: StaffSignupRoute,
  ApiWebhooksPaytechRoute: ApiWebhooksPaytechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
