/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConfirmationRegistrationIdRouteImport } from './routes/confirmation.$registrationId'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffSignupRouteImport } from './routes/staff.signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRegistrationIdRoute =
  ConfirmationRegistrationIdRouteImport.update({
    id: '/confirmation/$registrationId',
    path: '/confirmation/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff/signup',
  path: '/staff/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/confirmation/$registrationId': typeof ConfirmationRegistrationIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/signup': typeof StaffSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/inscription'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/inscription'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/inscription'
    | '/confirmation/$registrationId'
    | '/staff/login'
    | '/staff/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  ConfirmationRegistrationIdRoute: typeof ConfirmationRegistrationIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffSignupRoute: typeof StaffSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$registrationId': {
      id: '/confirmation/$registrationId'
      path: '/confirmation/$registrationId'
      fullPath: '/confirmation/$registrationId'
      preLoaderRoute: typeof ConfirmationRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/signup': {
      id: '/staff/signup'
      path: '/staff/signup'
      fullPath: '/staff/signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  ConfirmationRegistrationIdRoute: ConfirmationRegistrationIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffSignupRoute: StaffSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
